### ISSUE TITLE
Add Intrigue Core

### ISSUE THREAD

**Issue by jcran** [hahwul/WebHackersWeapons#14]
Repo: https://github.com/intrigueio/intrigue-core
Project Site: https://core.intrigue.io

Category: Discovery/ALL
Description: Intrigue Core is an open framework for discovering and enumerating the attack surface of organizations. It can be used with a human-in-the-loop running individual tasks, or fully automated through the use of machine files. With a flexible entity model and deep enrichment system, it is one of the most full-featured open source frameworks for discovering attack surface.

Let me know if you need more information!

**Comment by hahwul** [comment]
Hi @jcran 
Thank you for your good opinion. 
I saw it in nahamcon but i missing it. I'll add it soon! or you can send PR to this project.
(If you do PR, it's good because it stays in the Git contributor as well.)

If you don't send PR, please tell me. I'll take care of it :D 

1) Fork this repo, 
2) build binary on your env
```
$ go build add-tool.go
$ go build distribute-readme.go
```

3) Run `add-tool` and `distribute-readme`
```
$ ./add-tool -url https://github.com/intrigueio/intrigue-core
$ ./distribute-readme
..snip...
[ copy/paste this ] git add data.json README.md ; git commit -m 'distribute readme'; git push -u origin master
```

4) copy last line, past your shell (commit and push your forked repo)
5) open github.com your forked repo, send pull request to main repo

Cheers,

**Comment by jcran** [comment]
Got it okay, i'll give this a try and ping if i have trouble. Thanks @hahwul!

**Comment by hahwul** [comment]
@jcran 
Hi, friends
I added it. With gratitude, I added your name to footer!

![1414](https://user-images.githubusercontent.com/13212227/90365242-7628dc80-e0a0-11ea-9797-975ed5b653b4.png)
