### ISSUE TITLE
Add Scilla

### ISSUE THREAD

**Issue by edoardottt** [hahwul/WebHackersWeapons#26]
Hi! I would like to suggest my tool scilla.

[github.com/edoardottt/scilla](https://github.com/edoardottt/scilla)

It performs subdomain, dns and port enumeration.

Thanks

**Comment by hahwul** [comment]
Hi @edoardottt 
I'll add it soon! or you can send PR to this project.
(If you do PR, it's good because it stays in the Git contributor as well 😁😎)

If you don't send PR, please tell me. I'll take care of it :D

1) Fork this repo and clone 
```
$ git clone https://github.com/edoardottt/WebHackersWeapons
$ cd WebHackersWeapons
```
2) build binary on your env
```
$ make contribute
```
3) Run add-tool and distribute-readme
```
$ ./add-tool -url https://github.com/edoardottt/scilla
$ ./distribute-readme
..snip...
[ copy/paste this ] git add data.json README.md ; git commit -m 'distribute readme'; git push -u origin master
```
4) copy last line, past your shell (commit and push your forked repo)
5) open github.com your forked repo, send pull request to main repo

Cheers,

**Comment by edoardottt** [comment]
Done! :+1:

**Comment by hahwul** [comment]
@edoardottt 
Merged! thank you :D
